name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:

jobs:

  fetch-repo-and-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prls${increment}"
        id: version

  docker-login:
    runs-on: ubuntu-latest
    needs: fetch-repo-and-version
    steps:
      - name: GitHub Login Container Registry
        env:
          GITH_USER: ${{ github.actor }}
          GITH_PASSWORD: ${{ secrets.GITH_PASSWORD }}
        run: |
          echo "Iniciando login en github"
          echo $GITH_PASSWORD | docker login ghcr.io -u $GITH_USER --password-stdin
          echo "Fin del login"

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [fetch-repo-and-version, docker-login]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version (again)
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prls${increment}"
        id: version

      - name: Build Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t ghcr.io/jhamisruiz/dv-app-web:$NEW_VERSION .
          docker build -t ghcr.io/jhamisruiz/dv-app-web:latest .

      - name: Push Docker Image to GitHub Container Registry
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push ghcr.io/jhamisruiz/dv-app-web:$NEW_VERSION
          docker push ghcr.io/jhamisruiz/dv-app-web:latest

  deploy:

    # nedd first execute build-and-push-image
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH init Serever
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_VPS_AUTH }} << EOF
          docker login ghcr.io -u jhamisruiz -p ${{ secrets.GITH_PASSWORD }}
          docker stop app-web-container || true
          docker rm app-web-container || true
          docker rmi ghcr.io/jhamisruiz/dv-app-web:latest || true
          docker pull ghcr.io/jhamisruiz/dv-app-web:latest
          docker run -d --name app-web-container -p 8000:8080 ghcr.io/jhamisruiz/dv-app-web:latest
        EOF
